name: .NET Core

on:
  push:
    tags:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name : Publish
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
        dotnet pack -c Release -o packages EasyNow.ApiClient.WxPusher/EasyNow.ApiClient.WxPusher.csproj
        dotnet pack -c Release -o packages EasyNow.ApiClient.WxPusher.HttpClientFactory/EasyNow.ApiClient.WxPusher.HttpClientFactory.csproj
        dotnet nuget push "packages/*.nupkg" --skip-duplicate --source "github"
